export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const SET_OFFERED_PRODUCT_ID = "SET_OFFERED_PRODUCT_ID";
export const SET_PRODUCT_OFFER = "SET_PRODUCT_OFFER";
export const CANCEL_PRODUCT_OFFER = "CANCEL_PRODUCT_OFFER";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";